[default]
SECRET_KEY = "AF456732ewdsvb5yI&%$&¨*ÏJNBDZCAESGBN-U*&¨%*%$#RE#$RGVDSVbnmjy,iolkjhrsefji3rhg"
WTF_CSRF_SECRET_KEY = 'LMK%N¨J%EBTRbyh54764¢³ø£{←380940329r4utyhipµoj´]¢³²h9tp31ṕ2387tvVNFSDAF##T'
